package dev.bee.fsrs

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test

import java.nio.file.Files
import java.nio.file.Path

/**
 * Relative tolerance against the reference vectors.
 *
 * Relative rather than absolute because the quantities here span eleven orders of
 * magnitude — intervals from 1.3e-7 days to 36500 — so a single absolute tolerance
 * would be meaninglessly loose at the top of that range and impossible at the
 * bottom.
 *
 * 1e-9 is far tighter than the 1.4e-5 gap the generator measured between
 * upstream's own float32 and float64 evaluation, so it pins the port to the
 * mathematics rather than to a particular floating-point width.
 */
private const val RELATIVE_TOLERANCE = 1.0e-9

/**
 * The FSRS-7 engine's oracle.
 *
 * The vectors in `testdata/fsrs7-reference-cases.json` are generated by running
 * upstream's own `models/fsrs_v7.py` under PyTorch — see the generator script
 * beside them. That is the point: a fixture written by re-deriving the equations
 * would agree with this port whenever both made the same misreading, which is
 * precisely the failure it needs to catch. Driving upstream's code makes it an
 * independent check.
 */
class Fsrs7EngineFixtureTest {
    @Test
    fun generatedReferenceFixtureIsTheEngineOracle() {
        val root = asObject(Json.parse(Files.readString(referenceCasesPath())))

        assertEquals("FSRS-7", root["algorithm"])
        assertEquals(35, integer(root, "parameterCount"))

        // The fixture carries the parameter vector it was generated with, so a
        // change to the engine's defaults cannot silently pass against vectors
        // computed from different numbers.
        val fixtureParameters = doubleArray(asList(root["parameters"]))
        assertArrayAlmostEquals(
            "fixture parameters match the engine defaults",
            Fsrs7Parameters.latestDefaultValues(),
            fixtureParameters,
        )
        assertEquals(Fsrs7.STABILITY_MIN, number(root, "stabilityMin"), 0.0)
        assertEquals(Fsrs7.STABILITY_MAX, number(root, "stabilityMax"), 0.0)

        val engine = Fsrs7Engine.create(Fsrs7Parameters.of(fixtureParameters))
        val cases = asList(root["cases"])
        assertEquals(384, cases.size)

        var checked = 0
        for (rawCase in cases) {
            val testCase = asObject(rawCase)
            val name = text(testCase, "name")
            when (text(testCase, "kind")) {
                "forgettingCurve" -> assertForgettingCurve(engine, name, testCase)
                "initialState" -> assertInitialState(engine, name, testCase)
                "nextDifficulty" -> assertNextDifficulty(engine, name, testCase)
                "stabilityComponents" -> assertStabilityComponents(engine, name, testCase)
                "nextState" -> assertNextState(engine, name, testCase)
                "nextStateWithParameters" -> assertNextStateWithParameters(name, testCase)
                "interval" -> assertInterval(engine, name, testCase)
                "sequence" -> assertSequence(engine, name, testCase)
                else -> fail("Unknown fixture case kind for $name")
            }
            checked++
        }
        assertEquals("every fixture case was asserted", cases.size, checked)
    }

    private fun assertForgettingCurve(engine: Fsrs7Engine, name: String, testCase: Map<String, Any?>) {
        // Difficulty is irrelevant to the curve, so any valid value works here.
        val state = FsrsMemoryState(number(testCase, "stability"), 5.0)
        val actual = engine.retrievability(state, number(testCase, "elapsedDays"))
        assertAlmostEquals(name, number(testCase, "expectedRetrievability"), actual)
    }

    private fun assertInitialState(engine: Fsrs7Engine, name: String, testCase: Map<String, Any?>) {
        val state = engine.initialState(rating(testCase))
        assertAlmostEquals("$name stability", number(testCase, "expectedStability"), state.stability)
        assertAlmostEquals("$name difficulty", number(testCase, "expectedDifficulty"), state.difficulty)
    }

    private fun assertNextDifficulty(engine: Fsrs7Engine, name: String, testCase: Map<String, Any?>) {
        val actual = engine.nextDifficulty(number(testCase, "difficulty"), rating(testCase))
        assertAlmostEquals(name, number(testCase, "expectedDifficulty"), actual)
    }

    /**
     * The long-term and short-term branches, and the coefficient that blends them.
     *
     * Reconstructed from the blended result rather than read from a dedicated API,
     * because exposing the two branches publicly would freeze an internal detail of
     * the algorithm into the package's API. The reconstruction is exact:
     * `blended = c * long + (1 - c) * short`, so given the fixture's `c` and the
     * two branch values, the engine's blended output is fully determined and this
     * still localises a fault to a branch.
     */
    private fun assertStabilityComponents(engine: Fsrs7Engine, name: String, testCase: Map<String, Any?>) {
        val stability = number(testCase, "stability")
        val difficulty = number(testCase, "difficulty")
        val elapsedDays = number(testCase, "elapsedDays")

        val state = FsrsMemoryState(stability, difficulty)
        assertAlmostEquals(
            "$name retrievability",
            number(testCase, "expectedRetrievability"),
            engine.retrievability(state, elapsedDays),
        )

        val coefficient = number(testCase, "expectedTransitionCoefficient")
        val expectedBlend = coefficient * number(testCase, "expectedLongTermStability") +
            (1.0 - coefficient) * number(testCase, "expectedShortTermStability")
        val clamped = Math.min(Math.max(expectedBlend, Fsrs7.STABILITY_MIN), Fsrs7.STABILITY_MAX)

        val actual = engine.nextState(state, rating(testCase), elapsedDays)
        assertAlmostEquals("$name blended stability", clamped, actual.stability)
    }

    private fun assertNextState(engine: Fsrs7Engine, name: String, testCase: Map<String, Any?>) {
        val state = FsrsMemoryState(number(testCase, "stability"), number(testCase, "difficulty"))
        val actual = engine.nextState(state, rating(testCase), number(testCase, "elapsedDays"))
        assertAlmostEquals("$name stability", number(testCase, "expectedStability"), actual.stability)
        assertAlmostEquals("$name difficulty", number(testCase, "expectedDifficulty"), actual.difficulty)
    }

    /**
     * A case carrying its own parameter vector.
     *
     * These exist because two of upstream's guards — the cap of the failure branch
     * at the current stability, and the `max(failure, success)` on a pass — never
     * bind under the default parameters. Deleting both still satisfies every
     * default-parameter vector, which was verified by mutation before these cases
     * were added. A learner's fitted parameters are not the defaults, so the guards
     * are reachable in practice and are pinned here with a legal extreme vector.
     */
    private fun assertNextStateWithParameters(name: String, testCase: Map<String, Any?>) {
        val engine = Fsrs7Engine.create(Fsrs7Parameters.of(doubleArray(asList(testCase["parameters"]))))
        val state = FsrsMemoryState(number(testCase, "stability"), number(testCase, "difficulty"))
        val actual = engine.nextState(state, rating(testCase), number(testCase, "elapsedDays"))
        assertAlmostEquals("$name stability", number(testCase, "expectedStability"), actual.stability)
        assertAlmostEquals("$name difficulty", number(testCase, "expectedDifficulty"), actual.difficulty)
    }

    private fun assertInterval(engine: Fsrs7Engine, name: String, testCase: Map<String, Any?>) {
        val actual = engine.nextIntervalDays(
            number(testCase, "stability"),
            number(testCase, "desiredRetention"),
            Fsrs7.STABILITY_MAX,
        )
        assertAlmostEquals(name, number(testCase, "expectedIntervalDays"), actual)
    }

    /**
     * A folded sequence of reviews.
     *
     * Per-call vectors cannot catch state threaded wrongly between reviews — an
     * engine that returned the previous stability instead of the new one would pass
     * every single-step case and fail here on the second entry.
     */
    private fun assertSequence(engine: Fsrs7Engine, name: String, testCase: Map<String, Any?>) {
        val steps = asList(testCase["steps"])
        assertTrue("$name has steps", steps.size > 1)

        val first = asObject(steps[0])
        var state = engine.initialState(rating(first))
        assertAlmostEquals("$name step 0 stability", number(first, "stability"), state.stability)
        assertAlmostEquals("$name step 0 difficulty", number(first, "difficulty"), state.difficulty)

        for (index in 1 until steps.size) {
            val step = asObject(steps[index])
            state = engine.nextState(state, rating(step), number(step, "elapsedDays"))
            assertAlmostEquals("$name step $index stability", number(step, "stability"), state.stability)
            assertAlmostEquals("$name step $index difficulty", number(step, "difficulty"), state.difficulty)
        }
    }

    private fun assertAlmostEquals(message: String, expected: Double, actual: Double) {
        val scale = Math.max(Math.max(Math.abs(expected), Math.abs(actual)), 1.0e-12)
        val relative = Math.abs(expected - actual) / scale
        assertTrue(
            "$message: expected $expected but was $actual (relative difference $relative)",
            relative <= RELATIVE_TOLERANCE,
        )
    }

    private fun assertArrayAlmostEquals(message: String, expected: DoubleArray, actual: DoubleArray) {
        assertEquals("$message: length", expected.size, actual.size)
        for (index in expected.indices) {
            assertEquals("$message: index $index", expected[index], actual[index], 0.0)
        }
    }

    private fun referenceCasesPath(): Path {
        val modulePath = Path.of("testdata", "fsrs7-reference-cases.json")
        if (Files.exists(modulePath)) {
            return modulePath
        }
        return Path.of("bee-fsrs", "testdata", "fsrs7-reference-cases.json")
    }

    private fun rating(values: Map<String, Any?>): FsrsRating = FsrsRating.fromValue(integer(values, "rating"))

    private fun doubleArray(values: List<Any?>): DoubleArray {
        val out = DoubleArray(values.size)
        for (index in values.indices) {
            out[index] = number(values[index])
        }
        return out
    }

    @Suppress("UNCHECKED_CAST")
    private fun asObject(value: Any?): Map<String, Any?> = value as Map<String, Any?>

    @Suppress("UNCHECKED_CAST")
    private fun asList(value: Any?): List<Any?> = value as List<Any?>

    private fun text(values: Map<String, Any?>, key: String): String = values[key] as String

    private fun integer(values: Map<String, Any?>, key: String): Int = Math.round(number(values, key)).toInt()

    private fun number(values: Map<String, Any?>, key: String): Double = number(values[key])

    private fun number(value: Any?): Double {
        if (value is Number) {
            return value.toDouble()
        }
        throw IllegalArgumentException("Expected number but got $value")
    }
}
