#!/usr/bin/env python3
"""Generate Kani's similar-kanji TSV from Kiku's compact kanji database."""

from __future__ import annotations

import argparse
import gzip
import json
import tarfile
from pathlib import Path
from typing import Any, Iterable


KIKU_DB_TAR = "apps/docs/public/_kiku_db_main.tar"
KIKU_DB_MANIFEST = "apps/docs/public/_kiku_db_main_manifest.json"
KIKU_COMPACT_JSON_GZ = "kiku_db_kanji_compact.json.gz"
VISUALLY_SIMILAR_INDEX = 8
SOURCE = "kiku:wk-visually-similar"
KANJI_RANGES = (
    (0x3400, 0x4DBF),
    (0x4E00, 0x9FFF),
    (0xF900, 0xFAFF),
    (0x20000, 0x2FA1F),
    (0x30000, 0x3134F),
)


def is_kanji(value: str) -> bool:
    if len(value) != 1:
        return False
    cp = ord(value)
    return any(start <= cp <= end for start, end in KANJI_RANGES)


def load_compact_db(kiku_root: Path) -> dict[str, Any]:
    manifest_path = kiku_root / KIKU_DB_MANIFEST
    tar_path = kiku_root / KIKU_DB_TAR
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if KIKU_COMPACT_JSON_GZ not in manifest.get("files", {}):
        raise ValueError(f"{manifest_path} does not reference {KIKU_COMPACT_JSON_GZ}")

    with tarfile.open(tar_path, "r") as archive:
        member = archive.extractfile(KIKU_COMPACT_JSON_GZ)
        if member is None:
            raise ValueError(f"{tar_path} does not contain {KIKU_COMPACT_JSON_GZ}")
        compact_json = gzip.decompress(member.read()).decode("utf-8")
    data = json.loads(compact_json)
    if not isinstance(data, dict):
        raise ValueError("Kiku compact kanji DB must be a JSON object")
    return data


def similar_pairs(compact_db: dict[str, Any]) -> list[tuple[str, str, str]]:
    pairs: set[tuple[str, str, str]] = set()
    for kanji, compact_entry in compact_db.items():
        if not is_kanji(kanji) or not isinstance(compact_entry, list):
            continue
        if len(compact_entry) <= VISUALLY_SIMILAR_INDEX:
            continue
        visually_similar = compact_entry[VISUALLY_SIMILAR_INDEX]
        if not isinstance(visually_similar, list):
            continue
        for other in visually_similar:
            if not isinstance(other, str) or not is_kanji(other) or other == kanji:
                continue
            first, second = sorted((kanji, other))
            pairs.add((first, second, SOURCE))
    return sorted(pairs)


def write_tsv(pairs: Iterable[tuple[str, str, str]], output: Path, source_commit: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by tools/generate_similar_kanji_tsv.py",
        "# Source: Kiku apps/docs/public/_kiku_db_main.tar",
        f"# Kiku commit: {source_commit}",
        "# Shape: KanjiInfoCompact[8] visuallySimilar",
        "kanji_a\tkanji_b\tsource",
    ]
    lines.extend(f"{a}\t{b}\t{source}" for a, b, source in pairs)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_attribution(output: Path, source_commit: str, pair_count: int) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "\n".join(
            [
                "Similar kanji pairs transformed from Kiku's vendored kanji database.",
                "Kiku repository: https://github.com/youyoumu/kiku",
                f"Kiku source commit: {source_commit}",
                f"Transformed pair count: {pair_count}",
                f"Source files: {KIKU_DB_TAR} and {KIKU_DB_MANIFEST}",
                "Source shape: KanjiInfoCompact[8] visuallySimilar, generated by packages/note/preprocess/generate-kiku-db-main.ts.",
                "Kiku's visuallySimilar values are populated from WaniKani kanji pages by packages/note/preprocess/scrap-wk.ts.",
                "Kani vendors only this transformed TSV at runtime; it does not depend on Kiku note types or Kiku runtime code.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kiku-root", type=Path, required=True)
    parser.add_argument("--source-commit", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--attribution", type=Path, required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    pairs = similar_pairs(load_compact_db(args.kiku_root))
    write_tsv(pairs, args.output, args.source_commit)
    write_attribution(args.attribution, args.source_commit, len(pairs))


if __name__ == "__main__":
    main()
