#!/usr/bin/env python3

from __future__ import annotations

import gzip
import json
import tarfile
import tempfile
import unittest
from io import BytesIO
from pathlib import Path

from tools import generate_similar_kanji_tsv as generator


EXPECTED_KANJI_RANGES = (
    (0x3400, 0x4DBF),
    (0x4E00, 0x9FFF),
    (0xF900, 0xFAFF),
    (0x20000, 0x2A6DF),
    (0x2A700, 0x2B73F),
    (0x2B740, 0x2B81F),
    (0x2B820, 0x2CEAF),
    (0x2CEB0, 0x2EBEF),
    (0x2EBF0, 0x2EE5F),
    (0x2F800, 0x2FA1F),
    (0x30000, 0x3134F),
    (0x31350, 0x323AF),
    (0x323B0, 0x3347F),
)


def compact_entry(visually_similar: list[str]) -> list[object]:
    return [[], [], "", [], "", [], "", "", visually_similar, []]


class GenerateSimilarKanjiTsvTest(unittest.TestCase):
    def test_uses_exact_unicode_cjk_ideograph_block_bounds(self) -> None:
        self.assertEqual(EXPECTED_KANJI_RANGES, generator.KANJI_RANGES)
        for start, end in EXPECTED_KANJI_RANGES:
            self.assertTrue(generator.is_kanji(chr(start)))
            self.assertTrue(generator.is_kanji(chr(end)))
        for codepoint in (0x2A6E0, 0x2EE60, 0x2FA20, 0x33480):
            self.assertFalse(generator.is_kanji(chr(codepoint)))
        self.assertFalse(generator.is_kanji("日本"))
        self.assertFalse(generator.is_kanji("A"))

    def test_loads_kiku_tar_shape_and_deduplicates_pairs(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            public = root / "apps/docs/public"
            public.mkdir(parents=True)
            compact = {
                "拉": compact_entry(["麺", "謎", "kana", "拉"]),
                "麺": compact_entry(["拉"]),
                "語": compact_entry([]),
            }
            payload = gzip.compress(json.dumps(compact).encode("utf-8"))
            with tarfile.open(public / "_kiku_db_main.tar", "w") as archive:
                info = tarfile.TarInfo(generator.KIKU_COMPACT_JSON_GZ)
                info.size = len(payload)
                archive.addfile(info, BytesIO(payload))
            (public / "_kiku_db_main_manifest.json").write_text(
                json.dumps({"files": {generator.KIKU_COMPACT_JSON_GZ: {"start": 512, "end": 512 + len(payload) - 1, "size": len(payload)}}}),
                encoding="utf-8",
            )

            pairs = generator.similar_pairs(generator.load_compact_db(root))

            self.assertEqual(
                [("拉", "謎", generator.SOURCE), ("拉", "麺", generator.SOURCE)],
                pairs,
            )

    def test_bundled_pairs_are_complete_sorted_and_well_formed(self) -> None:
        output = Path("app/src/main/res/raw/similar_kanji.tsv")
        lines = output.read_text(encoding="utf-8").splitlines()
        self.assertEqual("# Generated by tools/generate_similar_kanji_tsv.py", lines[0])
        self.assertEqual("kanji_a\tkanji_b\tsource", lines[4])

        pairs = [tuple(line.split("\t")) for line in lines[5:]]

        self.assertEqual(2053, len(pairs))
        self.assertEqual(sorted(set(pairs)), pairs)
        self.assertTrue(
            all(
                len(pair) == 3
                and generator.is_kanji(pair[0])
                and generator.is_kanji(pair[1])
                and pair[0] < pair[1]
                and pair[2] == generator.SOURCE
                for pair in pairs
            )
        )


if __name__ == "__main__":
    unittest.main()
