package dev.bee.kanjianki.core

import org.junit.Assert.assertEquals
import org.junit.Test

class SettingsTextCopyDelegationTest {
    @Test
    fun wrapperDelegatesToExtractedHelpers() {
        val importSettings = settings(true, true, true, true, true, 3)
        assertEquals(
            listOf(
                SettingsSummaryTextCopy.settingsImportSummary(importSettings),
                SettingsSummaryTextCopy.matchingCardsSummary(importSettings),
                SettingsSummaryTextCopy.syncStatusHeadline(true, null, 4, 2),
                SettingsSummaryTextCopy.syncStatusHeadline(false, "No provider", 0, 0),
                SettingsAutomationTextCopy.settingsReminderSummary(true, false, "21:05"),
                SettingsAutomationTextCopy.autoSyncDetail(true, true, "yesterday", "today", "tomorrow"),
            ),
            listOf(
                SettingsTextCopy.settingsImportSummary(importSettings),
                SettingsTextCopy.matchingCardsSummary(importSettings),
                SettingsTextCopy.syncStatusHeadline(true, null, 4, 2),
                SettingsTextCopy.syncStatusHeadline(false, "No provider", 0, 0),
                SettingsTextCopy.settingsReminderSummary(true, false, "21:05"),
                SettingsTextCopy.autoSyncDetail(true, true, "yesterday", "today", "tomorrow"),
            ),
        )
        assertEquals(
            listOf(
                SettingsSectionTextCopy.settingsAnkiSourceTitle(),
                SettingsLearningTextCopy.learningStepsTitle(),
                SettingsImportFiltersTextCopy.importFiltersTitle(),
                SettingsReferenceDataTextCopy.frequencyRangeTitle(),
                SettingsStudyPlanTextCopy.newCardSortTitle(),
                SettingsStudyPlanTextCopy.newCardSortConfusablePreviewWarning(listOf("人/入")),
                SettingsStudyPlanTextCopy.deckLimitsTitle(),
                SettingsStudyPlanTextCopy.deckLimitsBody(),
                SettingsStudyPlanTextCopy.newCardsPerDayLabel(),
                SettingsStudyPlanTextCopy.saveDeckLimitsLabel(),
                SettingsStudyPlanTextCopy.fsrsRetentionTitle(),
                SettingsStudyPlanTextCopy.studyLadderTitle(),
                SettingsStudyAheadTextCopy.studyAheadTitle(),
                SettingsStudyAheadTextCopy.studyAheadBody(),
                SettingsStudyAheadTextCopy.saveStudyAheadLabel(),
                SettingsStudyAheadTextCopy.studyAheadSavedToast(),
                SettingsStudyAheadTextCopy.studyAheadMinutesLabel(),
                SettingsStudyAheadTextCopy.studyAheadMinutesRange(),
                SettingsStudyAheadTextCopy.studyAheadWholeNumberErrorText(),
                SettingsStudyAheadTextCopy.studyAheadOutOfRangeErrorText(),
                SettingsStudyAheadTextCopy.studyAheadMaxDescription(),
                SettingsLadderThresholdTextCopy.ladderThresholdsTitle(),
                SettingsLadderThresholdTextCopy.ladderThresholdsBody(),
                SettingsLadderThresholdTextCopy.fsrsDaysToGoUpLabel(),
                SettingsLadderThresholdTextCopy.failsToGoDownLabel(),
            ),
            listOf(
                SettingsTextCopy.settingsAnkiSourceTitle(),
                SettingsTextCopy.learningStepsTitle(),
                SettingsTextCopy.importFiltersTitle(),
                SettingsTextCopy.frequencyRangeTitle(),
                SettingsTextCopy.newCardSortTitle(),
                SettingsTextCopy.newCardSortConfusablePreviewWarning(listOf("人/入")),
                SettingsTextCopy.deckLimitsTitle(),
                SettingsTextCopy.deckLimitsBody(),
                SettingsTextCopy.newCardsPerDayLabel(),
                SettingsTextCopy.saveDeckLimitsLabel(),
                SettingsTextCopy.fsrsRetentionTitle(),
                SettingsTextCopy.studyLadderTitle(),
                SettingsTextCopy.studyAheadTitle(),
                SettingsTextCopy.studyAheadBody(),
                SettingsTextCopy.saveStudyAheadLabel(),
                SettingsTextCopy.studyAheadSavedToast(),
                SettingsTextCopy.studyAheadMinutesLabel(),
                SettingsTextCopy.studyAheadMinutesRange(),
                SettingsTextCopy.studyAheadWholeNumberErrorText(),
                SettingsTextCopy.studyAheadOutOfRangeErrorText(),
                SettingsTextCopy.studyAheadMaxDescription(),
                SettingsTextCopy.ladderThresholdsTitle(),
                SettingsTextCopy.ladderThresholdsBody(),
                SettingsTextCopy.fsrsDaysToGoUpLabel(),
                SettingsTextCopy.failsToGoDownLabel(),
            ),
        )
        assertEquals(
            listOf(
                SettingsLadderThresholdTextCopy.useDefaultLadderThresholdsLabel(),
                SettingsLadderThresholdTextCopy.saveLadderThresholdsLabel(),
                SettingsLadderThresholdTextCopy.ladderThresholdsSavedToast(),
                SettingsNoteTypeTextCopy.noteTypeFieldsTitle(),
                SettingsNoteTypeTextCopy.noteTypeUsingText("Kiku"),
                SettingsNoteTypeTextCopy.noteTypeFieldsBody(),
                SettingsNoteTypeTextCopy.requiredFieldsTitle(),
                SettingsNoteTypeTextCopy.requiredFieldsBody(),
                SettingsNoteTypeTextCopy.expressionFieldLabel(),
                SettingsNoteTypeTextCopy.readingFieldLabel(),
                SettingsNoteTypeTextCopy.meaningFieldLabel(),
                SettingsNoteTypeTextCopy.sentenceFieldLabel(),
                SettingsNoteTypeTextCopy.frequencyFieldLabel(),
                SettingsNoteTypeTextCopy.frequencySortFieldLabel(),
                SettingsNoteTypeTextCopy.chooseFromAnkiDroidLabel(),
                SettingsNoteTypeTextCopy.useKikuLabel(),
                SettingsNoteTypeTextCopy.saveNoteTypeLabel(),
                SettingsNoteTypeTextCopy.noteTypeRequiredToast(),
                SettingsNoteTypeTextCopy.expressionFieldRequiredToast(),
                SettingsNoteTypeTextCopy.noteTypeSavedToast(),
            ),
            listOf(
                SettingsTextCopy.useDefaultLadderThresholdsLabel(),
                SettingsTextCopy.saveLadderThresholdsLabel(),
                SettingsTextCopy.ladderThresholdsSavedToast(),
                SettingsTextCopy.noteTypeFieldsTitle(),
                SettingsTextCopy.noteTypeUsingText("Kiku"),
                SettingsTextCopy.noteTypeFieldsBody(),
                SettingsTextCopy.requiredFieldsTitle(),
                SettingsTextCopy.requiredFieldsBody(),
                SettingsTextCopy.expressionFieldLabel(),
                SettingsTextCopy.readingFieldLabel(),
                SettingsTextCopy.meaningFieldLabel(),
                SettingsTextCopy.sentenceFieldLabel(),
                SettingsTextCopy.frequencyFieldLabel(),
                SettingsTextCopy.frequencySortFieldLabel(),
                SettingsTextCopy.chooseFromAnkiDroidLabel(),
                SettingsTextCopy.useKikuLabel(),
                SettingsTextCopy.saveNoteTypeLabel(),
                SettingsTextCopy.noteTypeRequiredToast(),
                SettingsTextCopy.expressionFieldRequiredToast(),
                SettingsTextCopy.noteTypeSavedToast(),
            ),
        )
    }
}

private fun settings(
    importActiveCards: Boolean,
    importSuspendedCards: Boolean,
    importTaggedCards: Boolean,
    importWeakCards: Boolean,
    browserQueryCards: Boolean,
    minMatchingCardsPerKanji: Int,
): RecordsSyncModels.Settings {
    return RecordsSyncModels.Settings(
        "Kiku",
        "Mining",
        "Expression",
        "ExpressionReading",
        "MainDefinition",
        "Sentence",
        "Frequency",
        "FreqSort",
        21,
        2,
        RecordsBase.DEFAULT_SUSPENDED_RANK_MIN,
        RecordsBase.DEFAULT_SUSPENDED_RANK_MAX,
        24,
        3,
        RecordsBase.DEFAULT_WRITING_TRIGGER_MISS_DAYS,
        RecordsBase.DEFAULT_RECOGNITION_PROMOTION_PASSES,
        RecordsBase.DEFAULT_REAL_DUE_REVIEWS_TO_MOVE,
        importActiveCards,
        importSuspendedCards,
        importTaggedCards,
        listOf("leeches"),
        importWeakCards,
        RecordsBase.DEFAULT_IMPORT_WEAK_FSRS_DIFFICULTY,
        RecordsBase.DEFAULT_IMPORT_WEAK_LAPSES,
        minMatchingCardsPerKanji,
        browserQueryCards,
        if (browserQueryCards) "deck:Kiku" else "",
        RecordsBase.DEFAULT_NEW_CARD_SORT_MODE,
        RecordsBase.DEFAULT_LADDER_PROMOTION_INTERVAL_DAYS,
        RecordsBase.DEFAULT_LADDER_DEMOTION_FAIL_STREAK,
    )
}
